### ISSUE TITLE
пагінація

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/Blog#1]
https://github.com/TarasOstasha/Blog/blob/9c3e1aa6ea47d782fa3702bcb509c27fa8f76d1a/server/middleware/paginate.js#L43
- варто бути обережними з отриманням всіх записів. Це особливо не варто робити з сутностями, яких може бути дійсно багато, як товари або списки повідомлень, оскільки запит, що повертає величезну кількість даних і в базі, і при передачі по мережі, і на серваку в змінній з цими сутностями, і на фронті для збкрігання та рендеру, їсть багато ресурсів.

**Comment by TarasOstasha** [comment]
fixed
